
CREATE TABLE IF NOT EXISTS PERSONA (
    id SERIAL PRIMARY KEY,
    apellido VARCHAR(20) NOT NULL,
    edad INT NOT NULL
    );


CREATE TABLE IF NOT EXISTS NOVIAS (
    id SERIAL PRIMARY KEY,
    apellido VARCHAR(20) NOT NULL,
    edad INT NOT NULL,
    PERSONA_id INT NOT NULL,
    FOREIGN KEY (PERSONA_id) REFERENCES PERSONA(id)
    );

